let currentDocId=null;
const conversationSessionId=sessionStorage.getItem('orgCogSessionId')||`SESSION:${crypto.randomUUID?.()||Date.now()}`;sessionStorage.setItem('orgCogSessionId',conversationSessionId);
const api=async(path,options={})=>{if(location.protocol==='file:')throw new Error('برای اجرای قابلیت‌های زنده، فایل START_BUILD.bat را اجرا کنید. پیش‌نمایش گرافیکی در حالت فایل مستقیم فعال است.');const r=await fetch(path,{headers:{'content-type':'application/json','x-org-id':'ORG:SYN-001','x-person-id':'PER:SARA',...(options.headers||{})},...options});const data=await r.json();if(!r.ok)throw new Error(data.message||'خطا');return data};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const faLabel=value=>{const k=String(value??'');const m={now:'اکنون',next:'بعدی',watch:'تحت نظر',decision:'تصمیم',review:'بازبینی',attention:'توجه',ready:'آماده',needs_completion:'نیازمند تکمیل',not_ready:'آماده نیست',proposed:'پیشنهادی',proposed_for_human_review:'پیشنهادی برای بررسی انسانی',preparation_required:'نیازمند آماده‌سازی',ready_for_human_convening:'آماده تشکیل توسط انسان',ready_with_authority_blocks:'آماده با مانع اختیار',live:'فعال',planned:'برنامه‌ریزی‌شده',internal:'داخلی',owner:'مسئول موضوع',brief:'خلاصه مدیریتی',authority:'اختیار تصمیم',evidence:'شواهد',signal:'سیگنال',risk:'ریسک',warning:'هشدار'};return m[k]||k;};
const faGovernance=value=>{const k=String(value??'');const m={'Attention may shape a proposed management agenda, but agenda placement does not create decision authority or organizational commitment.':'اولویت توجه می‌تواند مبنای پیشنهاد دستورکار مدیریتی باشد؛ اما قرارگرفتن در دستورکار، اختیار تصمیم یا تعهد سازمانی ایجاد نمی‌کند.','Agenda readiness verifies preparation for a meeting; readiness does not convene the meeting or grant decision authority.':'ارزیابی آمادگی، شرایط لازم برای ورود موضوع به جلسه را بررسی می‌کند؛ آمادگی به‌خودی‌خود جلسه را تشکیل نمی‌دهد و اختیار تصمیم ایجاد نمی‌کند.','Meeting orchestration connects validated readiness to decision preparation; it does not convert a brief, agenda, or AI recommendation into a decision.':'آماده‌سازی جلسه، آمادگی معتبر را به فرایند تصمیم‌سازی متصل می‌کند؛ خلاصه، دستورکار یا پیشنهاد هوش مصنوعی به‌خودی‌خود تصمیم سازمانی نیست.'};return m[k]||k;};
const faIntent=value=>{const m={'workspace.cognitive_attention':'اولویت توجه مدیریت','workspace.management_agenda':'دستورکار مدیریتی','workspace.agenda_readiness':'آمادگی دستورکار','workspace.meeting_orchestration':'آماده‌سازی جلسه','workspace.focus_queue':'صف تمرکز شناختی','workspace.cognitive_brief':'جمع‌بندی شناختی','workspace.morning':'میز کار امروز','knowledge.inventory':'موجودی دانش','knowledge.list':'دانش و اسناد','document.analyze':'تحلیل اسناد'};return m[value]||'پاسخ هوشمند سازمانی';};


function ensureSourceDrawer(){
  let el=document.getElementById('sourceDrawer');
  if(el)return el;
  el=document.createElement('aside');el.id='sourceDrawer';el.className='source-drawer';
  el.innerHTML=`<div class="source-drawer-head"><div><small>بررسی منبع</small><b id="sourceDrawerTitle">منبع</b></div><button id="closeSourceDrawer">×</button></div><div id="sourceDrawerBody" class="source-drawer-body"></div>`;
  document.body.appendChild(el);
  el.querySelector('#closeSourceDrawer').onclick=()=>el.classList.remove('open');
  return el;
}
window.openEvidenceSource=async(ref)=>{
  if(!ref)return alert('مرجع منبع برای این مورد ثبت نشده است.');
  const drawer=ensureSourceDrawer(),body=drawer.querySelector('#sourceDrawerBody'),ttl=drawer.querySelector('#sourceDrawerTitle');
  ttl.textContent='در حال بازیابی منبع…';body.innerHTML='<div class="source-loading">در حال بررسی دسترسی و بازیابی رکورد…</div>';drawer.classList.add('open');
  try{
    const x=await api(`/api/v1/sources/${encodeURIComponent(ref)}`);
    ttl.textContent=x.found?`منبع · ${x.type}`:'منبع پیدا نشد';
    if(!x.found){body.innerHTML=`<div class="source-empty">${esc(x.provenanceNotice||'مرجع در دسترس نیست.')}</div>`;return;}
    const labels={id:'شناسه',title:'عنوان',status:'وضعیت',version:'نسخه',createdAt:'ایجاد',updatedAt:'آخرین تغییر',contentHash:'اثر انگشت محتوا',exactDuplicateOf:'تکرار دقیق از',priority:'اولویت',dueAt:'مهلت',assigneeRef:'مسئول',startAt:'زمان جلسه',reason:'دلیل هشدار',confidence:'اطمینان',kind:'نوع پیشنهاد',value:'مقدار',sourceLocation:'محل منبع',documentId:'سند'};
    const rows=Object.entries(x.data||{}).map(([k,v])=>`<div class="source-field"><span>${esc(labels[k]||k)}</span><b>${esc(typeof v==='object'?JSON.stringify(v):v)}</b></div>`).join('');
    body.innerHTML=`<div class="source-badge">${esc(x.access)} · ${esc(x.type)}</div><div class="source-fields">${rows}</div><div class="source-notice">${esc(x.provenanceNotice||'')}</div>${x.actions?.trace?`<button class="source-action" id="openSourceTrace">مشاهده Trace کامل سند</button>`:''}`;
    if(x.actions?.trace){body.querySelector('#openSourceTrace').onclick=async()=>{drawer.classList.remove('open');await loadTrace(x.ref);showView('trace');};}
  }catch(e){ttl.textContent='خطا در بازیابی منبع';body.innerHTML=`<div class="source-empty">${esc(e.message)}</div>`;}
};
function showView(view){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));const el=document.getElementById(view);if(el)el.classList.add('active');if(el)el.scrollIntoView({behavior:'smooth',block:'start'});}
async function refresh(){const d=await api('/api/v1/dashboard');document.querySelector('#stats').innerHTML=`<div class="stat"><span class="eyebrow">اسناد ثبت‌شده</span><strong>${d.stats.documents}</strong></div><div class="stat"><span class="eyebrow">نیازمند بررسی</span><strong>${d.stats.review}</strong></div><div class="stat"><span class="eyebrow">پذیرفته/اصلاح‌شده</span><strong>${d.stats.accepted}</strong></div>`;document.querySelector('#knowledgeList').innerHTML=d.recent.length?d.recent.map(x=>`<div class="doc"><h3>${esc(x.title)}</h3><small>${esc(x.id)} · نسخه ${x.version} · ${esc(x.status)}</small><div class="chips">${(x.canonicalMetadata?.topics||[]).map(t=>`<span class="chip">${esc(t)}</span>`).join('')}</div></div>`).join(''):'<div class="empty">هنوز سندی ثبت نشده است.</div>';return d;}
function candidateCard(c){const loc=c.sourceLocation?`<small class="muted">منبع: ${esc(Object.values(c.sourceLocation).filter(Boolean).join(' / '))}</small>`:'';return `<div class="candidate" id="${c.id}"><div class="type">${c.kind==='topic'?'موضوع پیشنهادی':'ادعای پیشنهادی'} · پیشنهاد هوش مصنوعی</div><div>${esc(c.value)}</div>${loc}<div class="buttons"><button class="small" onclick="review('${c.id}','accept')">تأیید</button><button class="small ghost" onclick="review('${c.id}','correct')">اصلاح</button><button class="small danger" onclick="review('${c.id}','reject')">رد</button></div></div>`}
window.review=async(id,action)=>{let value;if(action==='correct')value=prompt('مقدار اصلاح‌شده را وارد کنید:');if(action==='correct'&&!value)return;try{await api(`/api/v1/candidates/${encodeURIComponent(id)}/review`,{method:'POST',body:JSON.stringify({action,value})});const el=document.getElementById(id);el.classList.add(action==='reject'?'rejected':'accepted');el.querySelector('.buttons').innerHTML=`<span class="muted">${action==='accept'?'تأیید شد':action==='correct'?'اصلاح و ثبت شد':'رد شد'}</span>`;await refresh();await loadTrace()}catch(e){alert(e.message)}};
async function loadTrace(docId=currentDocId){if(docId)currentDocId=docId;if(!currentDocId)return;const t=await api(`/api/v1/documents/${encodeURIComponent(currentDocId)}/trace`);const steps=[['منبع',`${t.document.title} — hash ${t.document.contentHash.slice(0,12)}…${t.document.exactDuplicateOf?`<br>Exact duplicate of ${t.document.exactDuplicateOf}`:''}`],['فایل اصلی',t.artifact?`${esc(t.artifact.fileName)} · ${esc(t.artifact.mimeType)} · ${t.artifact.size} bytes`:'—'],['نسخه نرمال‌شده',`${t.normalized?.[0]?.structure?.kind||'—'} · ${t.normalized?.[0]?.unitCount||0} واحد ساختاری`],['دانش معتبر',`${t.document.id} — Version ${t.document.version}`],['اجرای هوش مصنوعی',t.aiExecutions.map(x=>`${x.model} / ${x.promptRef} / ${x.groundingStatus}`).join('<br>')||'—'],['پیشنهادها',`${t.candidates.length} پیشنهاد؛ ${t.candidates.filter(x=>['accepted','corrected'].includes(x.status)).length} پذیرفته/اصلاح‌شده<br>${t.candidates.slice(0,4).map(x=>`${esc(x.value)} ← ${esc(JSON.stringify(x.sourceLocation||{}))}`).join('<br>')}`],['ممیزی',`${t.audit.length} رکورد ممیزی`],['منشأ و ردیابی',`${t.provenance.length} رکورد منشأ و تبدیل`]];(document.querySelector('#traceView')||document.querySelector('#traceSteps')).innerHTML=steps.map(([a,b])=>`<div class="trace-step"><b>${a}</b><div>${b}</div></div>`).join('')}
const toBase64=file=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(file)});
document.querySelector('#runFlow').onclick=async()=>{const btn=document.querySelector('#runFlow'),status=document.querySelector('#flowStatus'),file=document.querySelector('#realFile').files[0];if(!file){status.textContent='ابتدا یک فایل انتخاب کنید.';return}btn.disabled=true;status.textContent='در حال خواندن و بارگذاری فایل…';try{const contentBase64=await toBase64(file);const up=await api('/api/v1/documents/upload',{method:'POST',body:JSON.stringify({title:document.querySelector('#docTitle').value,fileName:file.name,mimeType:file.type,contentBase64,knowledgeZone:'private',classification:'internal'})});const doc=up.document;currentDocId=doc.id;status.textContent=`فایل ذخیره و ${up.normalized.structure.kind} استخراج شد${up.document.exactDuplicateOf?'؛ فایل تکراری دقیق شناسایی شد':''}؛ در حال تحلیل…`;const p=await api(`/api/v1/documents/${encodeURIComponent(doc.id)}/process`,{method:'POST',body:'{}'});document.querySelector('#candidates').innerHTML=p.candidates.map(candidateCard).join('');status.textContent=`${p.candidates.length} پیشنهاد آماده بررسی است.`;await refresh();await loadTrace();document.querySelector('#commandResult').innerHTML=`<span class="intent-badge">document.analyze</span><h2>تحلیل فایل انجام شد</h2><p>${esc(doc.title)} با ${p.candidates.length} پیشنهاد آماده قضاوت شماست.</p>`}catch(e){status.textContent=e.message}finally{btn.disabled=false}};


function workspaceIcon(type){
 const map={focus_queue:'◎',cognitive_brief:'◈',attention_board:'✦',meeting_timeline:'▣',action_board:'✓',correspondence_list:'▱',document_grid:'□',trace_flow:'↗',document_action:'⇧',generic_cards:'◇'};
 return map[type]||'◇';
}
function itemIcon(meta){
 const map={work:'✓',meeting:'▣',inbox:'▱',review:'✦',alert:'!',document:'□'};
 return map[meta]||'◇';
}
function renderWorkspaceItems(result){
 const type=result.workspace?.componentType||'generic_cards';
 const w=result.workspace||{};
 const items=result.items||[];
 if(!items.length)return '<div class="workspace-empty">نتیجه‌ای برای نمایش وجود ندارد.</div>';
 if(type==='meeting_timeline'){
   return `<div class="meeting-timeline">${items.map((i,n)=>`<div class="meeting-row"><div class="time-dot"><span>${n+1}</span></div><div class="meeting-card"><div class="card-icon">▣</div><div><b>${esc(i.title)}</b><p>${esc(i.subtitle||'')}</p><small>${esc(i.meta||'جلسه')}</small></div></div></div>`).join('')}</div>`;
 }
 if(type==='action_board'){
   return `<div class="action-board">${items.map(i=>`<div class="action-card"><div class="check-ring">✓</div><div class="action-body"><b>${esc(i.title)}</b><p>${esc(i.subtitle||'')}</p><span class="mini-tag">${esc(i.meta||'کار')}</span></div></div>`).join('')}</div>`;
 }
 if(type==='correspondence_list'){
   return `<div class="mail-list">${items.map(i=>`<div class="mail-card"><div class="mail-icon">▱</div><div><b>${esc(i.title)}</b><p>${esc(i.subtitle||'')}</p><small>${esc(i.meta||'مکاتبه')}</small></div><span class="chev">‹</span></div>`).join('')}</div>`;
 }
 if(type==='document_grid'||type==='document_action'){
   return `<div class="document-grid">${items.map(i=>`<div class="document-card"><div class="document-symbol">□</div><div><b>${esc(i.title)}</b><p>${esc(i.subtitle||'')}</p><small>${esc(i.meta||'سند')}</small></div></div>`).join('')}</div>`;
 }
 if(type==='trace_flow'){
   return `<div class="trace-flow">${items.map((i,n)=>`<div class="trace-node"><span>${n+1}</span><div><b>${esc(i.title)}</b><p>${esc(i.subtitle||'')}</p><small>${esc(i.meta||'')}</small></div></div>`).join('')}</div>`;
 }
 if(type==='cross_object_workspace'){
   const sections=result.workspace?.sections||[];
   const icon={documents:'□',actions:'✓',meetings:'▣',correspondence:'▱',alerts:'!'};
   return `<div class="cross-workspace"><div class="cross-summary">${Object.entries(result.workspace?.summary||{}).filter(([k])=>k!=='total').map(([k,v])=>`<div><strong>${v}</strong><span>${({documents:'سند',actions:'کار',meetings:'جلسه',correspondence:'مکاتبه',attention:'مورد توجه'})[k]||k}</span></div>`).join('')}</div>${sections.map(s=>`<section class="cross-section"><div class="cross-section-head"><span class="cross-icon">${icon[s.key]||'◇'}</span><div><b>${esc(s.title)}</b><small>${s.sourceStatus==='connector_pending'?'منبع زنده هنوز متصل نیست':'داده قابل دسترس فعلی'}</small></div><span class="section-count">${s.items.length}</span></div><div class="cross-items">${s.items.length?s.items.map(i=>`<article><span class="card-icon">${itemIcon(i.meta||i.type)}</span><div><b>${esc(i.title)}</b><p>${esc(i.subtitle||'')}</p></div></article>`).join(''):`<div class="cross-empty">${s.sourceStatus==='connector_pending'?'Connector آماده اتصال است؛ نبود داده به معنی نبود مورد واقعی نیست.':'مورد مرتبطی پیدا نشد.'}</div>`}</div></section>`).join('')}</div>`;
 }
 if(type==='meeting_orchestration'){const o=w.orchestration||{},packs=o.agendaPacks||[],g=w.governance||{};return `<div class="meeting-orch"><div class="mo-head"><div><small>پل آماده‌سازی جلسه</small><h3>${esc(o.title||'جلسه شناختی سازمان')}</h3></div><span>${esc(faLabel(o.status||''))}</span></div><div class="mo-summary"><article><b>${packs.length}</b><small>موضوعات آماده</small></article><article><b>${o.authorityBlocked?.length||0}</b><small>موانع اختیار</small></article><article><b>${o.totalSuggestedMinutes||0}</b><small>دقیقه</small></article></div><div class="mo-flow">${packs.map(x=>`<article><div><b>${x.sequence}. ${esc(x.title)}</b><span>${esc(faLabel(x.mode))}</span></div><p>${esc(x.facilitation?.purpose||'')}</p><small>شواهد ${x.decisionBrief?.evidenceRefs?.length||0} · نیاز به چالش ${x.facilitation?.challengeRequired?'✓':'—'} · ثبت تصمیم ${x.facilitation?.decisionCaptureRequired?'✓':'—'}</small></article>`).join('')}</div><div class="mo-gate"><b>بسته آمادگی ≠ تصمیم</b><span>${esc(g.principle||'')}</span></div></div>`;}
if(type==='agenda_readiness'){const r=w.readiness||{},items=r.items||[],g=w.governance||{};return `<div class="agenda-ready"><div class="agr-head"><div><small>آمادگی دستورکار و پیش‌جلسه</small><h3>آمادگی دستورکار برای جلسه</h3></div><span>${esc(faLabel(r.status||''))}</span></div><div class="agr-summary"><article><b>${r.readyCount||0}</b><small>آماده</small></article><article><b>${r.incompleteCount||0}</b><small>نیازمند تکمیل</small></article><article><b>${r.preMeetingActions?.length||0}</b><small>اقدامات</small></article></div><div class="agr-items">${items.map(x=>`<article><div><b>${esc(x.title)}</b><span>${x.readinessScore}%</span></div><p>${esc(faLabel(x.readiness))}</p><small>موارد ناقص: ${(x.missing||[]).map(v=>esc(faLabel(v))).join(' · ')||'—'}</small></article>`).join('')}</div><div class="agr-gate"><b>آمادگی ≠ تشکیل جلسه</b><span>${esc(faGovernance(g.principle||''))}</span></div></div>`;}
if(type==='management_agenda'){const a=w.agenda||{},items=a.agendaItems||[],f=a.focusSummary||{},g=w.governance||{};return `<div class="management-agenda"><div class="ma-head"><div><small>توجه ← دستورکار مدیریتی</small><h3>${esc(a.title||'دستورکار شناختی پیشنهادی')}</h3></div><span>${esc(faLabel(a.status||''))}</span></div><div class="ma-summary"><article><b>${f.decision||0}</b><small>تصمیم</small></article><article><b>${f.review||0}</b><small>بازبینی</small></article><article><b>${f.attention||0}</b><small>توجه</small></article><article><b>${a.totalSuggestedMinutes||0}</b><small>دقیقه</small></article></div><div class="ma-items">${items.map((x,i)=>`<article><b>${i+1}. ${esc(x.title)}</b><span>${esc(faLabel(x.mode))}</span><p>${esc(x.purpose)}</p><small>امتیاز ${x.score} · ${x.suggestedMinutes} دقیقه · نیازمند شاهد</small></article>`).join('')}</div><div class="ma-gate"><b>دستورکار ≠ اختیار تصمیم</b><span>${esc(faGovernance(g.principle||''))}</span></div></div>`;}
if(type==='cognitive_attention'){
 const a=w.attention||{},q=a.queue||[],g=w.governance||{};
 return `<div class="cognitive-attention"><div class="ca-head"><div><small>اولویت شناختی توجه</small><h3>اکنون سازمان باید به چه چیزی توجه کند؟</h3></div><span>${q.length} سیگنال</span></div><div class="ca-windows"><article><b>${a.now?.length||0}</b><small>اکنون</small></article><article><b>${a.next?.length||0}</b><small>بعدی</small></article><article><b>${a.watch?.length||0}</b><small>تحت نظر</small></article></div><div class="ca-queue">${q.map(x=>`<article><div class="ca-rank">${x.rank}</div><section><div><b>${esc(x.title)}</b><span>${esc(faLabel(x.focusWindow))}</span></div><p>${(x.reason||[]).map(esc).join(' · ')}</p><small>${esc(faLabel(x.type))} · امتیاز ${x.score}</small></section></article>`).join('')}</div><div class="ca-gate"><b>توجه ≠ اختیار</b><span>${esc(g.principle||'')}</span><small>بدون رتبه‌بندی اشخاص</small></div></div>`;
}
if(type==='warning_evaluation'){
 const e=w.evaluation||{},c=e.calibration||{},g=w.governance||{};
 return `<div class="warning-eval"><div class="we-head"><div><small>Cognitive Warning Evaluation</small><h3>ارزیابی هشدار و یادگیری از واکنش سازمان</h3></div><span>${esc(e.validity||'')}</span></div><div class="we-grid"><article><b>${esc(e.severity||'')}</b><small>Severity</small></article><article><b>${e.response?.ignored?'بله':'خیر'}</b><small>Ignored</small></article><article><b>${e.observed?.eventOccurred===true?'رخ داد':e.observed?.eventOccurred===false?'رخ نداد':'نامشخص'}</b><small>Observed Event</small></article><article><b>${e.evidenceRefs?.length||0}</b><small>Evidence</small></article></div><div class="we-learning"><h4>گزاره‌های یادگیری پیشنهادی</h4>${(e.learningCandidates||[]).map(x=>`<article><span>${esc(x.type)}</span><p>${esc(x.claim)}</p></article>`).join('')||'<small>یادگیری جدیدی هنوز قابل طرح نیست.</small>'}</div><div class="we-cal"><b>تنظیم هشدار</b><span>Strengthen attention: ${c.strengthenFutureAttention?'yes':'no'}</span><span>Review threshold: ${c.reviewThreshold?'yes':'no'}</span><span>Automatic threshold change: no</span></div><div class="we-gate"><b>بازتنظیم انسانی الزامی است</b><span>${esc(g.principle||'')}</span></div></div>`;
}
if(type==='cognitive_reassessment'){
 const r=w.reassessment||{},cs=r.claims||[],loop=r.closedLoop||{},g=w.governance||{};
 return `<div class="cog-reassess"><div class="cr-head"><div><small>Cognitive Reassessment & Closed Learning Loop</small><h3>بازارزیابی شناخت سازمان</h3></div><span>${r.changedCount||0} نیازمند بازبینی</span></div><div class="cr-loop">${(loop.inputs||[]).map(x=>`<span>${esc(x)}</span><i>←</i>`).join('')}<b>${esc(loop.output||'')}</b></div><div class="cr-summary"><article><b>${r.stableCount||0}</b><small>Still Valid</small></article><article><b>${r.changedCount||0}</b><small>Review Needed</small></article><article><b>${loop.canonicalChangesApplied??0}</b><small>Auto Changes</small></article></div><div class="cr-claims">${cs.map(x=>`<article><div><b>${esc(x.title)}</b><span class="${esc(x.status)}">${esc(x.status)}</span></div><small>Confidence Δ ${x.confidenceDelta>0?'+':''}${x.confidenceDelta}</small><p>Supporting: ${x.evidence?.supporting?.length||0} · Challenging: ${x.evidence?.challenging?.length||0} · Memory: ${x.evidence?.memorySupport?.length||0}</p></article>`).join('')}</div>${r.realitySignals?.length?`<div class="cr-reality"><b>Reality Signals</b>${r.realitySignals.map(x=>`<span>• ${esc(x)}</span>`).join('')}</div>`:''}<div class="cr-gate"><b>Human Cognitive Review</b><span>${esc(g.principle||'')}</span><small>Canonical cognition changed automatically: no</small></div></div>`;
}
if(type==='memory_retrieval'){
 const r=w.retrieval||{},items=r.results||[],g=w.governance||{};
 return `<div class="memory-retrieval"><div class="mr-head"><div><small>بازیابی و استفاده مجدد از حافظه شناختی</small><h3>حافظه مرتبط با وضعیت فعلی</h3></div><span>${items.length} memory</span></div><div class="mr-query"><b>زمینه فعلی</b><p>${esc(r.query||'—')}</p><small>${(r.contexts||[]).map(esc).join(' · ')||'بدون Context صریح'}</small></div><div class="mr-list">${items.length?items.map(x=>`<article><div class="mr-score"><b>${x.score}</b><small>match</small></div><section><div class="mr-title"><b>${esc(x.title)}</b><span>${esc(x.reuse)}</span></div><p>${esc(x.claim)}</p><small>${(x.reasons||[]).map(esc).join(' · ')}</small><div class="mr-tags"><i>Context ${x.match?.context??0}%</i><i>Validity ${x.match?.valid?'✓':'!'}</i><i>Evidence ${x.evidenceRefs?.length||0}</i><i>Confidence ${esc(x.confidence||'')}</i></div></section></article>`).join(''):'<div class="mr-empty">حافظه معتبر و مرتبطی برای این وضعیت بازیابی نشد.</div>'}</div><div class="mr-gate"><b>Reuse ≠ Automatic Application</b><span>${esc(g.principle||'')}</span><small>Memory is evidence, not authority.</small></div></div>`;
}
if(type==='validated_memory'){
 const m=w.memory||{},rp=w.reusePolicy||{},g=w.governance||{};
 return `<div class="validated-memory"><div class="vm-head"><div><small>یادگیری سازمانی و حافظه اعتبارسنجی‌شده</small><h3>${esc(m.title||'حافظه سازمانی')}</h3></div><span>${esc(m.status||w.status||'')}</span></div>${m.claim?`<div class="vm-claim"><b>گزاره یادگیری اعتبارسنجی‌شده</b><p>${esc(m.claim)}</p><small>Confidence: ${esc(m.confidence||'')} · Evidence: ${m.evidenceRefs?.length||0}</small></div>`:''}<div class="vm-grid"><section><h4>زمینه</h4>${(m.contexts||[]).map(x=>`<span>${esc(x)}</span>`).join('')||'<small>—</small>'}</section><section><h4>شرایط اعتبار</h4>${(m.conditions||[]).map(x=>`<p>• ${esc(x)}</p>`).join('')||'<small>—</small>'}</section><section><h4>بازه اعتبار</h4><p>از: ${esc(m.validFrom||'—')}</p><p>تا: ${esc(m.validUntil||'باز')}</p></section></div><div class="vm-reuse"><b>سیاست استفاده مجدد</b><div>${Object.entries(rp).map(([k,v])=>`<span class="${v?'yes':'no'}">${v?'✓':'○'} ${esc(k)}</span>`).join('')}</div></div><div class="vm-gate"><b>حافظه وابسته به زمینه</b><span>${esc(g.principle||'')}</span><small>Canonical memory ≠ universal truth</small></div></div>`;
}
if(type==='anchor_realization'){
 const r=w.realization||{},h=r.health||{},c=r.contribution||{},g=w.governance||{};
 const pct=r.realizationPercent==null?0:Math.max(0,Math.min(100,r.realizationPercent));
 return `<div class="anchor-real"><div class="ar-head"><div><small>به‌روزرسانی تحقق لنگر</small><h3>${esc(r.title||'تحقق Anchor')}</h3></div><span>${esc(faLabel(r.status||''))}</span></div><div class="ar-progress"><div class="ar-ring"><b>${r.realizationPercent??'—'}%</b><small>Realization</small></div><section><div class="ar-bar"><i style="width:${pct}%"></i></div><p>Baseline: ${r.baseline??'—'} · Current: ${r.current??'—'} · Target: ${r.target??'—'}</p><small>Remaining Gap: ${r.remainingGap??'—'} · Confidence: ${esc(r.confidence||'')}</small></section></div><div class="ar-metrics"><article><b>${r.velocity??'—'}</b><small>Realization Velocity</small></article><article><b>${r.requiredVelocity??'—'}</b><small>Required Velocity</small></article><article><b>${r.forecastedDaysToTarget??'—'}</b><small>Days to Target</small></article><article><b>${r.evidenceRefs?.length||0}</b><small>Evidence</small></article></div><div class="ar-contrib"><b>بهبود مشاهده‌شده در برابر انتساب</b><p>بهبود مشاهده‌شده: ${c.observedImprovement??'—'} · سهم منتسب سازمان: ${c.attributedOrganizationalContribution??'تعیین نشده'}</p><small>${esc(c.status||'')}</small></div><div class="ar-gate"><b>حکمرانی لنگر</b><span>${esc(g.principle||'')}</span><small>Anchor auto-revision: no · Sustainable: ${h.sustainable?'yes':'no'} · Fragile: ${h.fragile?'yes':'no'}</small></div></div>`;
}
if(type==='outcome_learning'){
 const l=w.learning||{},r=l.resultModel||{},c=l.causalAssessment||{},claims=l.learningClaims||[],g=w.governance||{};
 return `<div class="outcome-learning"><div class="ol-head"><div><small>Outcome & Causal Learning</small><h3>یادگیری از نتیجه</h3></div><span>${esc(r.type||'outcome')}</span></div><div class="ol-chain"><article><small>Baseline</small><b>${r.baseline??'—'}</b></article><i>←</i><article><small>Expected</small><b>${r.expected??'—'}</b></article><i>←</i><article><small>Observed</small><b>${r.observed??'—'}</b></article><i>←</i><article><small>Counterfactual</small><b>${r.counterfactual??'—'}</b></article></div><div class="ol-causal"><section><h4>Attribution</h4><b>${esc(c.attribution?.status||'')}</b><small>تأیید علّی: خیر</small>${(c.attribution?.blockers||[]).map(x=>`<p>• ${esc(x)}</p>`).join('')}</section><section><h4>Contribution</h4><b>${esc(c.contribution?.status||'')}</b><small>شواهد: ${c.contribution?.evidenceCount||0}</small><p>عامل بیرونی: ${c.externalFactors?.length||0} · مداخله هم‌زمان: ${c.concurrentInterventions?.length||0}</p></section></div><div class="ol-claims"><h4>گزاره‌های یادگیری پیشنهادی</h4>${claims.map(x=>`<article><span>${esc(x.confidence)}</span><div><b>${esc(x.type)}</b><p>${esc(x.claim)}</p></div></article>`).join('')}</div><div class="ol-gate"><b>Human Learning Validation</b><span>${esc(g.principle||'')}</span><small>Organizational memory: candidate only</small></div></div>`;
}
if(type==='failure_diagnosis'){
 const d=w.diagnosis||{},bt=d.backtrack||[],hs=d.hypotheses||[],ca=d.correctiveActions||[],g=w.governance||{};
 return `<div class="failure-dx"><div class="fd-head"><div><small>Non-Achievement & Failure Diagnosis</small><h3>تشخیص عدم تحقق</h3></div><span>${esc(d.classification||'')}</span></div><div class="fd-path">${bt.map((x,i)=>`<div><b>${esc(x.layer)}</b><small>${esc(x.status)}</small>${i<bt.length-1?'<i>←</i>':''}</div>`).join('')}</div><div class="fd-cols"><section><h4>فرضیه‌های علّی</h4>${hs.length?hs.map(x=>`<article><span>${x.level?`L${x.level}`:'?'}</span><div><b>${esc(x.type)}</b><p>${esc(x.claim)}</p><small>وضعیت: hypothesis</small></div></article>`).join(''):'<p class="fd-empty">برای انتساب علت، شواهد کافی وجود ندارد.</p>'}</section><section><h4>اقدامات اصلاحی پیشنهادی</h4>${ca.length?ca.map(x=>`<p>• ${esc(x)}</p>`).join(''):'<p class="fd-empty">نیازمند تکمیل تشخیص</p>'}</section></div><div class="fd-gate"><b>Human Causal Validation</b><span>${esc(d.attribution?.principle||g.principle||'Diagnosis ≠ causal proof.')}</span><small>Confirmed cause: none</small></div></div>`;
}
if(type==='execution_monitoring'){
 const m=w.monitoring||{},pk=m.packages||[],dev=m.deviations||[],g=w.governance||{};
 return `<div class="exec-monitor"><div class="em-head"><div><small>پایش اجرا</small><h3>پایش اجرای تصمیم</h3></div><span class="${esc(m.health||'')}">${esc(m.health||'')}</span></div><div class="em-summary"><article><b>${m.progress||0}%</b><small>پیشرفت گزارش‌شده</small></article><article><b>${pk.length}</b><small>Work Package</small></article><article><b>${dev.length}</b><small>انحراف</small></article></div><div class="em-packages">${pk.map(x=>`<article><div class="em-row"><b>${esc(x.title)}</b><span>${x.progress}%</span></div><div class="em-bar"><i style="width:${x.progress}%"></i></div><small>${esc(x.status)} · مسئول: ${esc(x.ownerRef||'—')} · شاهد: ${x.evidenceRefs?.length||0}</small>${x.deviations?.length?`<div class="em-dev">${x.deviations.map(d=>`<p>⚠ ${esc(d.message)}</p>`).join('')}</div>`:''}</article>`).join('')}</div><div class="em-gate"><b>پایش مبتنی بر شواهد</b><span>${esc(g.principle||'')}</span><small>Reported progress ≠ proven outcome</small></div></div>`;
}
if(type==='authorized_execution'){
 const e=w.executionPlan||{},r=w.readiness||{},wps=e.workPackages||[],g=w.governance||{};
 return `<div class="authorized-exec"><div class="ae-head"><div><small>Authorized Execution Plan</small><h3>${esc(e.id||'برنامه اجرای مجاز')}</h3></div><span>${r.score!=null?`${r.score}% readiness`:esc(w.status||'')}</span></div><div class="ae-packages"><h4>Work Packages</h4>${wps.map((x,i)=>`<article><div class="ae-num">${i+1}</div><section><b>${esc(x.title)}</b><small>R: ${esc(x.raci?.responsible||'—')} · A: ${esc(x.raci?.accountable||'—')} · مهلت: ${esc(x.dueAt||'—')}</small><p>منابع: ${x.allocatedResources?.length||0} · KPI: ${x.kpis?.length||0} · Milestone: ${x.milestones?.length||0}</p><span>${esc(x.status)}</span></section></article>`).join('')}</div><div class="ae-status"><div><b>${e.canonical?'✓':'○'}</b><span>Canonical Plan</span></div><div><b>${g.executionMayStart?'✓':'○'}</b><span>اجازه شروع</span></div><div><b>${g.monitoringRequired?'✓':'○'}</b><span>نظارت الزامی</span></div><div><b>${e.started?'✓':'○'}</b><span>شروع واقعی</span></div></div><div class="ae-principle">${esc(g.principle||'')}</div></div>`;
}
if(type==='decision_to_action'){
 const p=w.plan||{},f=w.fidelity||{},g=w.governance||{},acts=p.actions||[],gaps=f.gaps||[];
 return `<div class="decision-action"><div class="da-head"><div><small>Decision-to-Action Translation</small><h3>${esc(p.decisionText||w.message||'ترجمه تصمیم به اقدام')}</h3></div><span>${f.score!=null?`${f.score}% fidelity`:'نیازمند تصمیم تأییدشده'}</span></div>${acts.length?`<div class="da-actions"><h4>اقدامات پیشنهادی</h4>${acts.map((x,i)=>`<article><div>${i+1}</div><section><b>${esc(x.title)}</b><small>مسئول: ${esc(x.ownerRef||'نامشخص')} · مهلت: ${esc(x.dueAt||'نامشخص')}</small><p>شواهد: ${x.evidenceRefs?.length||0} · وابستگی‌ها: ${x.dependencies?.length||0} · canonical: no</p></section></article>`).join('')}</div>`:''}${f.score!=null?`<div class="da-fidelity"><div class="da-score"><b>${f.score}</b><small>Decision Translation Fidelity</small></div><div class="da-checks">${Object.entries(f.checks||{}).map(([k,v])=>`<span class="${v?'ok':'miss'}">${v?'✓':'○'} ${esc(k)}</span>`).join('')}</div></div>`:''}${gaps.length?`<div class="da-gaps"><b>شکاف‌های ترجمه</b>${gaps.map(x=>`<div>• ${esc(x)}</div>`).join('')}</div>`:''}<div class="da-gate"><b>Human Approval Required</b><span>${esc(g.principle||'Draft action plan ≠ authorized execution.')}</span></div></div>`;
}
if(type==='decision_confirmation'){
 const g=w.gate||{},d=w.decision||{},bl=w.blockers||[];
 return `<div class="decision-confirm"><div class="dc-head"><div><small>Authorized Decision Capture</small><h3>${w.status==='confirmed'?'تصمیم تأییدشده':'دروازه تأیید تصمیم'}</h3></div><span class="${w.status==='confirmed'?'ok':'blocked'}">${esc(w.status||'')}</span></div>${d.text?`<div class="dc-decision"><b>Decision Record</b><p>${esc(d.text)}</p><small>${esc(d.id||'')} · canonical: ${d.canonical?'yes':'no'}</small></div>`:''}${bl.length?`<div class="dc-blockers"><b>شرایط تکمیل‌نشده</b>${bl.map(x=>`<div>• ${esc(x)}</div>`).join('')}</div>`:''}<div class="dc-gate"><div><b>${g.humanConfirmed?'✓':'○'}</b><span>تأیید انسانی</span></div><div><b>${g.authorized?'✓':'○'}</b><span>اختیار معتبر</span></div><div><b>${g.authorityRef?'✓':'○'}</b><span>مرجع اختیار</span></div><div><b>${g.evidenceCount||0}</b><span>شاهد</span></div></div><div class="dc-principle">${esc(w.principle||'')}</div></div>`;
}
if(type==='live_meeting'){
 const m=w.meeting||{},obs=w.observations||[],dc=w.decisionCandidates||[],ac=w.actionCandidates||[],warn=w.evidenceWarnings||[],g=w.governance||{};
 return `<div class="live-meeting"><div class="lm-head"><div><small>Live Meeting Intelligence</small><h3>${esc(m.title||'جلسه زنده')}</h3></div><span class="lm-live">● LIVE COGNITIVE SUPPORT</span></div><div class="lm-grid"><article><b>${obs.length}</b><small>مشاهده ثبت‌شده</small></article><article><b>${dc.length}</b><small>نامزد تصمیم</small></article><article><b>${ac.length}</b><small>نامزد اقدام</small></article><article><b>${warn.length}</b><small>هشدار شاهد</small></article></div><div class="lm-stream"><h4>جریان شناختی جلسه</h4>${obs.length?obs.map(x=>`<div class="lm-ob"><span>${esc(x.id)}</span><div><b>${esc(x.classification)}</b><p>${esc(x.text)}</p><small>شاهد: ${esc(x.evidenceStatus)} · canonical: no</small></div></div>`).join(''):'<div class="lm-empty">هنوز گزاره‌ای برای تحلیل حین جلسه ثبت نشده است.</div>'}</div>${warn.length?`<div class="lm-warnings"><h4>هشدارهای شاهد</h4>${warn.map(x=>`<div>⚠ ${esc(x.message)}</div>`).join('')}</div>`:''}<div class="lm-gate"><b>Human Confirmation Gate</b><span>${esc(g.principle||'')}</span><small>Canonical decisions: ${g.canonicalDecisionsCreated||0} · Canonical actions: ${g.canonicalActionsCreated||0}</small></div></div>`;
}
if(type==='pre_meeting'){
 const m=w.meeting||{},sum=w.executiveSummary||{},ag=w.agenda||[],qs=w.meetingQuestions||[],g=w.governance||{};
 return `<div class="pre-meeting"><div class="pm-head"><div><small>هوشمندی پیش از جلسه</small><h3>${esc(m.title||'جلسه')}</h3><span>${esc(m.startAt||'زمان ثبت نشده')}</span></div><div class="pm-stats"><b>${sum.agendaItems||0}</b><small>موضوع</small><b>${sum.readyForHumanReview||0}</b><small>آماده مرور</small></div></div><div class="pm-agenda"><h4>دستور شناختی جلسه</h4>${ag.map((x,i)=>`<article><div class="pm-num">${i+1}</div><div><b>${esc(x.title)}</b><p>${esc(x.reason||'')}</p><small>شواهد: ${x.evidenceCount} · آمادگی: ${esc(x.decisionReadiness?.level||'نامشخص')}</small>${x.ref?`<button class="open-source-btn" onclick="openEvidenceSource('${esc(x.ref)}')">منبع</button>`:''}</div></article>`).join('')}</div><div class="pm-questions"><h4>پرسش‌هایی که جلسه باید پاسخ دهد</h4>${qs.map(x=>`<div>؟ ${esc(x)}</div>`).join('')}</div><div class="pm-governance"><b>ریاست انسانی جلسه الزامی است</b><span>${esc(g.principle||'')}</span><small>Decisions created: ${g.decisionsCreated||0} · Minutes created: ${g.minutesCreated?'yes':'no'}</small></div></div>`;
}
if(type==='decision_brief'){
 const b=w.brief||{},g=w.governance||{},ev=b.evidence||[],unc=b.uncertainties||[],opts=b.options||[];
 return `<div class="decision-brief"><div class="db-head"><div><small>بسته آمادگی تصمیم</small><h3>${esc(w.subject?.title||'موضوع تصمیم')}</h3></div><span>پیش‌نویس شناختی</span></div><div class="db-question">${esc(b.executiveQuestion||'')}</div><div class="db-section"><h4>صورت مسئله</h4><p>${esc(b.problemFrame?.statement||'')}</p>${b.problemFrame?.sourceRef?`<button class="open-source-btn" onclick="openEvidenceSource('${esc(b.problemFrame.sourceRef)}')">باز کردن منبع</button>`:''}</div><div class="db-columns"><section><h4>شواهد</h4>${ev.length?ev.map(x=>`<div class="db-row"><b>${esc(x.id)}</b><span>${esc(x.value)}</span></div>`).join(''):'<div class="db-empty">شاهد صریح کافی ثبت نشده است.</div>'}</section><section><h4>ابهام‌های باز</h4>${unc.length?unc.map(x=>`<div class="db-row warn"><span>${esc(x)}</span></div>`).join(''):'<div class="db-empty">ابهام ثبت‌شده‌ای در این سطح وجود ندارد.</div>'}</section></div><div class="db-section"><h4>گزینه‌های فعلی</h4><div class="db-options">${opts.map(o=>`<article><b>${esc(o.title)}</b><small>${esc(o.status)}</small><p>${esc(o.basis)}</p></article>`).join('')}</div></div><div class="db-columns"><section><h4>موانع پیش از تصمیم</h4>${(b.blockers||[]).map(x=>`<div class="db-row warn"><span>${esc(x)}</span></div>`).join('')}</section><section><h4>چک‌لیست تکمیل</h4>${(b.preDecisionChecklist||[]).map((x,i)=>`<div class="db-row"><b>${i+1}</b><span>${esc(x)}</span></div>`).join('')}</section></div><div class="db-governance"><b>دروازه تأیید انسانی</b><span>${esc(g.principle||'')}</span><small>Decision created: ${g.decisionCreated?'yes':'no'} · Authority granted: ${g.authorityGranted?'yes':'no'}</small></div></div>`;
}
if(type==='decision_readiness'){
 const r=w.readiness||{},dims=w.dimensions||[],blocks=w.blockers||[],steps=w.requiredNextSteps||[];
 const badge=r.level==='ready_for_review'?'آماده برای مرور انسانی':r.level==='not_ready'?'آماده نیست':'نیازمند تکمیل';
 return `<div class="decision-readiness"><div class="dr-head"><div><small>آمادگی تصمیم</small><h3>${esc(w.subject?.title||'موضوع تصمیم')}</h3></div><span class="dr-badge ${esc(r.level||'')}">${badge}</span></div><div class="dr-score"><b>${r.score==null?'—':r.score}</b><span>امتیاز آمادگی</span><small>این امتیاز مجوز تصمیم نیست</small></div><div class="dr-grid">${dims.map(d=>`<article class="dr-card"><div class="dr-card-top"><b>${esc(d.title)}</b><span>${esc(d.status)}</span></div><div class="dr-meter"><i style="width:${Number.isFinite(d.score)?Math.max(0,Math.min(100,d.score)):0}%"></i></div><p>${esc(d.note||'')}</p></article>`).join('')}</div><div class="dr-lists"><section><h4>موانع آمادگی</h4>${blocks.length?blocks.map(x=>`<div class="dr-item">• ${esc(x)}</div>`).join(''):'<div class="dr-item">مورد مسدودکننده‌ای ثبت نشده است.</div>'}</section><section><h4>گام‌های بعدی</h4>${steps.map((x,i)=>`<div class="dr-item">${i+1}. ${esc(x)}</div>`).join('')}</section></div><div class="dr-principle">${esc(w.principle||'آمادگی تصمیم ≠ Decision Authority')}</div></div>`;
}
if(type==='focus_queue'){
   return `<div class="focus-queue">${items.map((i,n)=>`<article class="focus-item">
     <div class="focus-rank">${n+1}</div>
     <div class="focus-main"><div class="focus-top"><b>${esc(i.title)}</b>${i.attentionScore!=null?`<span class="focus-score">${Math.round(i.attentionScore)}</span>`:''}</div>
     ${i.subtitle?`<p>${esc(i.subtitle)}</p>`:''}
     <div class="focus-reason"><span>چرا مهم است؟</span>${esc(i.reason||'')}</div>
     <div class="focus-next"><span>اقدام بعدی</span>${esc(i.nextAction||'بررسی و تصمیم‌گیری')}</div>
     <div class="focus-meta">${i.confidence!=null?`اطمینان ${Math.round(i.confidence*100)}٪`:''}${i.sourceType?` · منبع: ${esc(i.sourceType)}`:''}</div>
     <details class="evidence-details"><summary>چرا؟ · مشاهده زنجیره شواهد</summary><div class="evidence-chain">${(i.provenance?.reasoning||[
       {label:'منبع',value:i.ref||'مرجع صریح در دسترس نیست'},
       {label:'شاهد',value:(i.evidence||[]).length?`${i.evidence.length} شاهد ثبت‌شده`:'فقط مرجع ساختاری موجود است'},
       {label:'استدلال',value:i.reason||''},
       {label:'اقدام پیشنهادی',value:i.nextAction||''}
     ]).map((s,ix)=>`<div class="evidence-step"><span>${ix+1}</span><div><b>${esc(s.label)}</b><p>${esc(s.value||'')}</p></div></div>`).join('')}</div><div class="cognitive-path"><div class="path-title">مسیر شناختی</div><div class="path-nodes">${(i.provenance?.cognitivePath?.nodes||[]).map((n,ix)=>`<div class="path-node"><span>${esc(n.label)}</span>${ix<(i.provenance?.cognitivePath?.nodes||[]).length-1?'<i>←</i>':''}</div>`).join('')}</div></div><div class="evidence-note">این مسیر از زمینه و داده‌های قابل‌دسترسی مشتق شده است؛ پیشنهاد سامانه جایگزین تصمیم سازمانی نیست. AI Candidate ≠ Organizational Truth.</div>${i.ref?`<button class="open-source-btn" onclick="openEvidenceSource('${esc(i.ref)}')">باز کردن منبع اصلی</button>`:''}</details></div>
   </article>`).join('')}</div>`;
 }
 if(type==='cognitive_brief'){
   return `<div class="cognitive-brief">${items.map((i,n)=>`<article class="brief-card"><div class="brief-number">0${n+1}</div><div><b>${esc(i.title)}</b><p>${esc(i.subtitle||'')}</p>${i.reason?`<div class="brief-reason">${esc(i.reason)}</div>`:''}${i.confidence!=null?`<small>اطمینان ${Math.round(i.confidence*100)}٪</small>`:''}</div></article>`).join('')}</div>`;
 }
 if(type==='attention_board'){
   return `<div class="attention-board">${items.map((i,n)=>`<article class="attention-card ${n<3?'priority':''}"><div class="attention-rank">${n+1}</div><div class="attention-content"><div class="attention-title"><span class="card-icon">${itemIcon(i.meta)}</span><b>${esc(i.title)}</b></div><p>${esc(i.subtitle||'')}</p>${i.reason?`<div class="why"><span>چرا مهم است؟</span>${esc(i.reason)}</div>`:''}<div class="attention-foot"><small>${esc(i.meta||'')}</small>${i.confidence!=null?`<span class="confidence">اطمینان ${Math.round(i.confidence*100)}٪${i.score?` · امتیاز ${i.score}`:''}</span>`:''}</div></div></article>`).join('')}</div>`;
 }
 return `<div class="result-grid">${items.map(i=>`<div class="result-card"><div class="card-icon">${itemIcon(i.meta)}</div><b>${esc(i.title)}</b><div>${esc(i.subtitle||'')}</div><small>${esc(i.meta||'')}</small>${i.reason?`<div class="reason">چرا مهم است؟ ${esc(i.reason)}</div>`:''}${i.confidence!=null?`<small class="confidence">اطمینان ${Math.round(i.confidence*100)}٪</small>`:''}</div>`).join('')}</div>`;
}
function renderCommandResult(result){
 const stage=document.querySelector('#commandResult');
 stage.classList.remove('hidden');
 const type=result.workspace?.componentType||'generic_cards';
 stage.dataset.workspace=type;
 stage.innerHTML=`<div class="workspace-head"><div class="workspace-title"><span class="workspace-icon">${workspaceIcon(type)}</span><div><span class="intent-badge">${esc(faIntent(result.intent))}</span><h2>${esc(result.title)}</h2><small>${result.status==='planned'?'قابلیت شناسایی شده؛ منبع زنده هنوز متصل نیست.':'نتیجه بر اساس داده‌های قابل دسترس و مجاز فعلی'}</small></div></div><div class="workspace-actions"><button title="بازخوانی">↻</button><button title="بیشتر">•••</button></div></div>${renderWorkspaceItems(result)}<div class="answer-actions"><button title="مفید بود">♡ مفید</button><button title="کپی خلاصه">⧉ کپی</button><span class="status-pill">قابل ردیابی</span></div>`;
 stage.scrollIntoView({behavior:'smooth',block:'center'});
}

const resizeCommandInput=input=>{if(!input)return;input.style.height='auto';const max=180,min=64;const wanted=Math.max(min,Math.min(input.scrollHeight,max));input.style.height=wanted+'px';input.style.overflowY=input.scrollHeight>max?'auto':'hidden';};
async function executeCommand(text){const input=document.querySelector('#commandInput');const q=String(text??input.value).trim();if(!q)return;input.value=q;resizeCommandInput(input);const stage=document.querySelector('#commandResult');stage.classList.remove('hidden');stage.innerHTML='<div class="answer-head"><span class="ai-orb">✦</span><div><h2>در حال بررسی</h2><div class="thinking"><span>زمینه، دسترسی و قابلیت مناسب</span><i></i><i></i><i></i></div></div></div>';try{const result=await api('/api/v1/command',{method:'POST',body:JSON.stringify({text:q,channel:'text',sessionId:conversationSessionId})});renderCommandResult(result);saveHistory(q,result);if(result.nextAction?.documentId)await loadTrace(result.nextAction.documentId);if(result.nextAction?.view)showView(result.nextAction.view);}catch(e){document.querySelector('#commandResult').innerHTML=`<h2>فرمان اجرا نشد</h2><p>${esc(e.message)}</p>`}}
document.querySelector('#runCommand').onclick=()=>executeCommand();document.querySelector('#commandInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();executeCommand();}});document.querySelectorAll('[data-command]').forEach(b=>b.onclick=()=>executeCommand(b.dataset.command));document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));

const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;const voiceBtn=document.querySelector('#voiceCommand'),voiceStatus=document.querySelector('#voiceStatus');if(!SpeechRecognition){voiceBtn.disabled=true;voiceBtn.title='تشخیص صوت در این مرورگر در دسترس نیست';voiceStatus.textContent='فرمان صوتی در این مرورگر پشتیبانی نمی‌شود؛ فرمان متنی فعال است.';}else{const rec=new SpeechRecognition();rec.lang='fa-IR';rec.interimResults=false;rec.continuous=false;rec.onstart=()=>{voiceBtn.classList.add('listening');voiceStatus.textContent='در حال شنیدن…';};rec.onend=()=>{voiceBtn.classList.remove('listening');if(voiceStatus.textContent==='در حال شنیدن…')voiceStatus.textContent='';};rec.onerror=e=>{voiceStatus.textContent=`خطای تشخیص صوت: ${e.error}`;};rec.onresult=e=>{const text=e.results[0][0].transcript;document.querySelector('#commandInput').value=text;voiceStatus.textContent=`شنیدم: «${text}»`;executeCommand(text);};voiceBtn.onclick=()=>rec.start();}
if(location.protocol==='file:'){
 const hint=document.querySelector('#runtimeHint');if(hint){hint.hidden=false;hint.innerHTML='پیش‌نمایش گرافیکی فعال است · برای اتصال قابلیت‌ها <b>START_BUILD.bat</b> را اجرا کنید.';}
}else{refresh().catch(e=>console.warn(e.message));}

async function runBatchUpload(){
 const files=[...document.querySelector('#realFile').files]; const status=document.querySelector('#flowStatus');
 if(!files.length){status.textContent='حداقل یک فایل انتخاب کنید.';return}
 status.textContent=`در حال آماده‌سازی ${files.length} فایل…`;
 try{
  const payload=[]; for(const file of files){payload.push({title:file.name,fileName:file.name,mimeType:file.type,contentBase64:await toBase64(file),knowledgeZone:'private',classification:'internal'});}
  const job=await api('/api/v1/documents/batch-upload',{method:'POST',body:JSON.stringify({files:payload})});
  status.textContent=`Batch تکمیل شد: ${job.completed}/${job.total} موفق، ${job.failed} خطا.`;
  document.querySelector('#commandResult').innerHTML=`<span class="intent-badge">knowledge.batch_intake</span><h2>ورود گروهی تکمیل شد</h2><p>${job.completed} فایل وارد شد؛ ${job.failed} خطا. Job: ${esc(job.id)}</p>`;
  await refresh();
 }catch(e){status.textContent=e.message}
}
document.querySelector('#runBatch')?.addEventListener('click',runBatchUpload);

document.querySelector('#commandInput')?.addEventListener('input',e=>resizeCommandInput(e.target));resizeCommandInput(document.querySelector('#commandInput'));
document.querySelector('#attachBtn')?.addEventListener('click',()=>{showView('home');setTimeout(()=>document.querySelector('#realFile')?.click(),100);});
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('.view')?.classList.remove('active'));
document.querySelectorAll('.view').forEach(v=>v.addEventListener('click',e=>{if(e.target===v)v.classList.remove('active')}));

const historyKey='orgCogRecentCommandsV1';
function readHistory(){try{return JSON.parse(localStorage.getItem(historyKey)||'[]')}catch{return []}}
function saveHistory(text,result){const a=readHistory().filter(x=>x.text!==text);a.unshift({text,intent:result.intent,at:new Date().toISOString()});localStorage.setItem(historyKey,JSON.stringify(a.slice(0,8)));renderHistory()}
function renderHistory(){const el=document.querySelector('#historyPanel');if(!el)return;const a=readHistory();el.innerHTML=a.length?a.map(x=>`<button class="history-item" data-history="${esc(x.text)}">${esc(x.text)}<small>${esc(x.intent)}</small></button>`).join(''):'<div class="history-item">هنوز گفت‌وگویی ثبت نشده است.</div>';el.querySelectorAll('[data-history]').forEach(b=>b.onclick=()=>{document.querySelector('#historyPanel').classList.remove('open');executeCommand(b.dataset.history)})}
document.querySelector('#historyToggle')?.addEventListener('click',()=>document.querySelector('#historyPanel')?.classList.toggle('open'));renderHistory();

document.querySelector('#analyzeDocs')?.addEventListener('click',()=>{showView('home');setTimeout(()=>document.querySelector('#realFile')?.focus(),80);});
