import {unzipEntries,xmlText} from './officeZip.js';
const textMime=['text/plain','text/markdown','text/csv'];
function pdfLite(buf){let s=buf.toString('latin1');const out=[];for(const m of s.matchAll(/\(([^()]*(?:\\.[^()]*)*)\)\s*Tj/g))out.push(m[1].replace(/\\([()\\])/g,'$1'));for(const m of s.matchAll(/\[(.*?)\]\s*TJ/gs)){for(const x of m[1].matchAll(/\(([^()]*)\)/g))out.push(x[1]);}return out.join(' ').trim();}
const parasFromText=(text,kind='text')=>String(text).split(/\n+/).map(x=>x.trim()).filter(Boolean).map((text,i)=>({text,locationPointer:{kind,index:i+1}}));
export async function parseArtifact({buffer,mimeType,fileName}){
  const lower=fileName.toLowerCase(); let text='',structure={kind:'unknown'},units=[];
  if(textMime.includes(mimeType)||lower.endsWith('.txt')||lower.endsWith('.md')||lower.endsWith('.csv')){text=buffer.toString('utf8');structure={kind:'text'};units=parasFromText(text,'line');}
  else if(lower.endsWith('.docx')){const z=unzipEntries(buffer),xml=z.get('word/document.xml');if(!xml)throw new Error('DOCX_DOCUMENT_XML_MISSING');const raw=String(xml);const ps=[...raw.matchAll(/<w:p\b[^>]*>(.*?)<\/w:p>/gs)].map((m,i)=>({text:xmlText(m[1]),locationPointer:{kind:'docx_paragraph',paragraph:i+1}})).filter(x=>x.text);units=ps;text=ps.map(x=>x.text).join('\n')||xmlText(xml);structure={kind:'docx',paragraphCount:ps.length};}
  else if(lower.endsWith('.pptx')){const z=unzipEntries(buffer);const slides=[...z.entries()].filter(([n])=>/^ppt\/slides\/slide\d+\.xml$/.test(n)).sort(([a],[b])=>a.localeCompare(b,undefined,{numeric:true})).map(([n,b],i)=>({slide:i+1,text:xmlText(b)}));text=slides.map(x=>x.text).join('\n');units=slides.filter(x=>x.text).map(x=>({text:x.text,locationPointer:{kind:'pptx_slide',slide:x.slide}}));structure={kind:'pptx',slides};}
  else if(lower.endsWith('.xlsx')){const z=unzipEntries(buffer);const shared=z.get('xl/sharedStrings.xml');const strings=shared?[...String(shared).matchAll(/<t[^>]*>(.*?)<\/t>/gs)].map(m=>xmlText(m[1])):[];const sheets=[...z.entries()].filter(([n])=>/^xl\/worksheets\/sheet\d+\.xml$/.test(n)).sort(([a],[b])=>a.localeCompare(b,undefined,{numeric:true})).map(([n,b],i)=>{const xml=String(b);const cells=[];for(const m of xml.matchAll(/<c([^>]*)r="([^"]+)"([^>]*)>(.*?)<\/c>/gs)){const attrs=(m[1]||'')+(m[3]||''),ref=m[2],inner=m[4],type=/t="s"/.test(attrs)?'s':'';const vm=inner.match(/<v>(.*?)<\/v>/s);let value=vm?vm[1]:'';if(type==='s'&&strings[Number(value)]!==undefined)value=strings[Number(value)];if(value)cells.push({ref,value});}return {sheet:i+1,cells};});units=sheets.flatMap(s=>s.cells.map(c=>({text:String(c.value),locationPointer:{kind:'xlsx_cell',sheet:s.sheet,cell:c.ref}})));text=units.map(x=>`Sheet ${x.locationPointer.sheet} ${x.locationPointer.cell}: ${x.text}`).join('\n');structure={kind:'xlsx',sheets};}
  else if(lower.endsWith('.pdf')||mimeType==='application/pdf'){text=pdfLite(buffer);structure={kind:'pdf',parser:'text-layer-lite'};if(!text) throw Object.assign(new Error('PDF_TEXT_LAYER_NOT_EXTRACTABLE'),{code:'PDF_TEXT_LAYER_NOT_EXTRACTABLE'});units=parasFromText(text,'pdf_text_segment');}
  else throw Object.assign(new Error('FILE_TYPE_UNSUPPORTED'),{code:'FILE_TYPE_UNSUPPORTED'});
  return {text:text.trim(),units,structure,language:/[\u0600-\u06FF]/.test(text)?'fa':'unknown'};
}
