import { createRepository } from '../src/infrastructure/repositoryFactory.js';
import { requireAuthenticated } from '../src/infrastructure/authSession.js';
const send=(res,s,d)=>{res.statusCode=s;res.setHeader('content-type','application/json; charset=utf-8');res.end(JSON.stringify(d))};
const norm=s=>String(s??'').normalize('NFKC').replace(/[يى]/g,'ی').replace(/ك/g,'ک').replace(/[\u200c\u200d]/g,' ').replace(/\s+/g,' ').trim().toLowerCase();
const digits=s=>String(s??'').replace(/[۰-۹]/g,d=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(d))).replace(/[٠-٩]/g,d=>String('٠١٢٣٤٥٦٧٨٩'.indexOf(d)));
const stop=new Set('در از به را رو برای درباره مورد مربوط مرتبط سند اسناد مصوبه مصوبات بگو بگید بیار بیاور نشان نمایش بده کن لطفا لطفاً چی چه چیزی آمده اومده گفته شده است هست آیا مثلا مثلاً و یا که این آن یک متن محتوای'.split(/\s+/));
const scopes=[['چشم‌انداز',['چشم انداز','چشم‌انداز']],['مأموریت',['مأموریت','ماموریت']],['اهداف کلان',['اهداف کلان','هدف کلان']],['سیاست',['سیاست']],['راهبرد',['راهبرد']],['آیین‌نامه',['آیین نامه','آیین‌نامه']],['بخشنامه',['بخشنامه']],['صورتجلسه',['صورتجلسه','صورت جلسه']]];
const scopeOf=q=>{const n=norm(q);for(const [label,alts] of scopes)if(alts.some(a=>n.includes(norm(a))))return{label,alts};return null};
const termsOf=(q,sc)=>{let n=norm(q);for(const a of(sc?.alts||[]))n=n.replaceAll(norm(a),' ');n=n.replace(/جلسه\s*(?:شماره)?\s*[۰-۹٠-٩0-9]+/g,' ');return[...new Set(n.split(/[^\p{L}\p{N}]+/u).filter(x=>x.length>1&&!stop.has(x)))]};
const sentences=t=>String(t||'').replace(/\r/g,'\n').split(/(?<=[.!؟؛])\s+|\n+/u).map(x=>x.trim()).filter(x=>x.length>12);
export default async function handler(req,res){
 if(!requireAuthenticated(req,res)) return;try{
 if(req.method!=='GET')return send(res,405,{message:'Method not allowed'});
 const repo=createRepository(),org=String(req.headers['x-org-id']||'ORG:SYN-001'),u=new URL(req.url,'https://local'),question=String(u.searchParams.get('question')||u.searchParams.get('q')||''),mode=u.searchParams.get('mode')||'search',db=await repo.all();
 const textByDoc=new Map();for(const x of(db.normalizedDocuments||[])){const id=x.documentRef||x.documentId||x.sourceDocumentRef,txt=String(x.text||x.content||x.normalizedText||'');if(id&&txt.length>(textByDoc.get(id)||'').length)textByDoc.set(id,txt)}
 const sc=scopeOf(question),terms=termsOf(question,sc),meeting=norm(question).match(/جلسه\s*(?:شماره)?\s*([۰-۹٠-٩0-9]+)/)?.[1]||'';
 let docs=(db.documents||[]).filter(d=>d.organizationId===org).map(d=>{const md=d.canonicalMetadata||d.metadata||{},text=textByDoc.get(d.id)||String(d.content||''),meta=norm([d.title,md.documentType,md.subjectArea].join(' '));let ss=0;if(sc)for(const a of sc.alts){const n=norm(a);if(norm(d.title).includes(n))ss+=6;if(norm(md.documentType).includes(n))ss+=5;if(meta.includes(n))ss+=2}return{d,md,text,ss}});
 if(sc)docs=docs.filter(x=>x.ss>0);if(meeting)docs=docs.filter(x=>digits(x.md.meetingNumber||'')===digits(meeting));
 if(mode==='qa'){let ev=[];for(const x of docs){for(const [i,s] of sentences(x.text).entries()){const n=norm(s);let score=0,h=0;for(const t of terms)if(n.includes(t)){score+=4;h++}if(terms.length&&h===terms.length)score+=10;if(score)ev.push({documentId:x.d.id,documentTitle:x.d.title,text:s,location:`بخش ${i+1}`,score})}}ev.sort((a,b)=>b.score-a.score);ev=ev.slice(0,6);const scopeLabel=sc?`سند/اسناد ${sc.label}`:'بانک اسناد';const summary=ev.length?`در ${scopeLabel} برای موضوع «${terms.join(' ')}» ${ev.length} شاهد متنی مرتبط پیدا شد.`:docs.length?`${scopeLabel} پیدا شد، اما شاهد متنی صریحی برای موضوع پرسش پیدا نشد.`:'سند موردنظر پیدا نشد.';return send(res,200,{answer:{summary,scopeLabel,evidence:ev},items:docs.slice(0,12).map(x=>({id:x.d.id,title:x.d.title,documentType:x.md.documentType||null,subjectArea:x.md.subjectArea||null,meetingNumber:x.md.meetingNumber||null,meetingDate:x.md.meetingDate||null,meetingType:x.md.meetingType||null,promulgationDate:x.md.promulgationDate||null}))})}
 let items=[];for(const x of docs){const hay=norm([x.d.title,x.md.documentType,x.md.subjectArea,x.md.issuer,x.text].join(' '));if(terms.length&&!terms.some(t=>hay.includes(t)))continue;const ss=sentences(x.text).filter(s=>terms.some(t=>norm(s).includes(t)));items.push({id:x.d.id,title:x.d.title,documentType:x.md.documentType||null,subjectArea:x.md.subjectArea||null,meetingNumber:x.md.meetingNumber||null,meetingDate:x.md.meetingDate||null,meetingType:x.md.meetingType||null,promulgationDate:x.md.promulgationDate||null,excerpt:ss[0]||String(x.text).slice(0,360)})}return send(res,200,{items:items.slice(0,30)});
}catch(e){console.error(e);return send(res,400,{message:e.message||'خطای جستجو و پرسش از اسناد'})}}